### ISSUE TITLE
Generate API models with swagger

### ISSUE THREAD

**Issue by NeaGogu** [NeaGogu/B-zone#2]
~~Have a look at https://github.com/go-swagger/go-swagger~~ to see how to generate models based on bumbal's swagger specification ( https://api-docs.freightlive.eu/ )

**Comment by Lucasmeteenc** [comment]
API Endpoints from Bumbal:
- log (only if we need to post sth on their endpoints)
- address-applied (to see the address where the activity was)
- route-points (to see the current points on a route)
- users (to use for retrieving customer data and displaying it)
- route (for the zones)
- zone (obviously)
- activity (retrieve all the activities)
- address (for the zones)
- authenticate (obviously)

API Endpoints from us:
- zone
  C (POST) zone\max-travel-time
  C (POST) zone\min-overlap
  C (POST) zone\max-zones
  C (POST) zone\min-zones
  M (POST) zone\save
  M (POST) zone\load
  M (GET) zone\computation
- map
  M (GET) map\location-data
- heatmap
  S (GET) heatmap\service-types
  C (GET) heatmap\k-closest
  M (GET) heatmap\activities
  M (GET) heatmap\activity-time
- comparison
  M (POST) comparison\fuel-cost
  M (GET) comparison\zone-comparison

**Comment by NeaGogu** [comment]
I couldn't make  https://github.com/go-swagger/go-swagger work (it considered bumbal's swagger spec as invalid). Was able to generate the models with https://github.com/swagger-api/swagger-codegen which at a first glance seems fine. Will investigate a bit more.
