### ISSUE TITLE
S.2.0 Define and implement MongoDB structure

### ISSUE THREAD

**Issue by Patricijia** [NeaGogu/B-zone#51]
It includes the structure of the database and queries such as SQL.
This task is related to the S.2

**Comment by NeaGogu** [comment]
Whats the status on this @Patricijia ?

**Comment by Patricijia** [comment]
![image](https://user-images.githubusercontent.com/64141509/224333479-b6c69713-2a8f-45ef-9f1b-f795216246a0.png)
Shouldn't we have zipcodes as folder?

**Comment by Patricijia** [comment]
We have structure in theory but not sure if there should be something in the code for the folders set up. I can do it based on the zipcodes @NeaGogu 
![image](https://user-images.githubusercontent.com/64141509/224333905-72d961e6-a76f-4074-87e5-2145998bcac5.png)

**Comment by NeaGogu** [comment]
Ill move this to done
